### PR TITLE
Logging Buffer Overrun Fix

### LINKED ISSUE #13: Log Handling Subsystem
# Description
We need to implement a logging solution to aid in debugging as well as track the state of the firmware in production. Logging will be performed through a UDP configured socket. In the case that the system is offline (offline detection required), logs will be sent over SPI to the SD card. The logging subsystem will be provisioned a single socket for logging.

The production systems will be a logging client streaming logs to a log aggregator such as [Loki](https://grafana.com/oss/loki/). Debug releases will have a socket server which can be connected to in order to view the active logs:
```bash
socat - UDP:192.168.2.34:4000
1643325325.55223 DEBUG main:10 Executing scheduled state caching job
1643325326.46846 CRITICAL eeprom_read:18 EEPROM read to address 0x56 failed
...
```

### PR DESCRIPTION
**Pull request by ztnel**
# Description
Fix buffer overrun bug in the logger modules string building function. The `MAX_LOGGING_LINE_LENGTH` macro is now 1 less than the total supported size to accommodate for the null byte delimiter. The string building function was tested for log lines greater than and less than the maximum length set by `MAX_LOGGING_LINE_LENGTH`

## Resolutions
 - [x] Fix buffer overrun in the logger module string building functions
 - [x] Add template `.clangd` configuration file in `utils`

## Issues
closes #13

### CODE REVIEW

File: src/logger.c [hunk 1]
```diff
@@ -151,8 +150,9 @@ void logger_task(void *pv_params) {
       if (client_fd < 0) {
         continue;
       }
-      build_log_string(&log);
-      ssize_t bytes_sent = send(client_fd, &log.message, strlen(log.message), 0);
+      char buffer[MAX_LOGGING_LINE_LEN];
```
Comment (BrandonLucasZhu) [inline src/logger.c:153]: `char buffer[MAX_LOGGING_LINE_LEN] = {0}`
Zero initialization for char buffer array if you want
