### PR TITLE
BME280 Driver and HAL I2C Clock Fixes

### LINKED ISSUE #35: BME280 `HAL_I2C_Mem_Read` failed read on T1,T2 and T3 calibration bytes
# Description
When I run my `test-bme280` test binary in real-time, the first block of calibration data loads correctly except for the first 3 bytes:
```
print bme280.calib_data
$1 = {dig_t1 = 0x0, dig_t2 = 0x0, dig_t3 = 0x0, dig_p1 = 0x94ca, dig_p2 = 0xd6bc, dig_p3 = 0xbd0, dig_p4 = 0x2441, dig_p5 = 0xff66, dig_p6 = 0xfff9, dig_p7 = 0x26ac, dig_p8 = 0xd80a, dig_p9 = 0x10bd, dig_h1 = 0x0, dig_h2 = 0x186, dig_h3 = 0x0, dig_h4 = 0x101, dig_h5 = 0x32, dig_h6 = 0x1e, t_fine = 0x0}
```
The first 3 bytes correspond to `T1` `T2` and `T3` and are 0. This causes the raw temperature data to unconditionally be 0 after conversion. 
However when I run the debugger and step through the following line:
```c
  status = HAL_I2C_Mem_Read(&dev->i2c, BME280_DEFAULT_DEV_ADDR, BME280_CALIB00, I2C_MEMADD_SIZE_8BIT, rx_buf, BME280_CALIB_BLK0_SIZE, HAL_MAX_DELAY);
```
The calibration values are all loaded correctly:
```
print bme280.calib_data
$2 = {dig_t1 = 0x6e2e, dig_t2 = 0x68b5, dig_t3 = 0x32, dig_p1 = 0x94ca, dig_p2 = 0xd6bc, dig_p3 = 0xbd0, dig_p4 = 0x2441, dig_p5 = 0xff66, dig_p6 = 0xfff9, dig_p7 = 0x26ac, dig_p8 = 0xd80a, dig_p9 = 0x10bd, dig_h1 = 0x0, dig_h2 = 0x186, dig_h3 = 0x0, dig_h4 = 0x101, dig_h5 = 0x32, dig_h6 = 0x0, t_fine = 0x0}
```

I have reproduced this test using both `cortex-debug` and `CubeIDE`. It is recommended to use a logic analyzer to confirm the data transactions performed while the firmware runs in real-time. There seems to be an issue with the timing of the I2C bus transactions.

### LINKED ISSUE #36: HAL Clock Configuration
# Description
The source firmware does not configure the clocking in the HAL library correctly. This is evident because the HAL library behaves as expected when stepping using a debugger but does not work when executed in real-time. This was particularly evident when using the HAL for I2C transactions. In real-time operations the transactions appear to complete instantaneously and yield all null values (no transactions performed?) However when using the debugger and stepping through the `HAL_I2C_Mem_Read` function, the program seems to properly implement I2C delays and returns expected transaction values.

### PR DESCRIPTION
**Pull request by ztnel**
# Description
This PR addresses failures in calibration loads from the BME280 sensor. The reason for the calibration load failure was because the sensor was still loading trimming parameters from its non-volatile memory (NVM) storage into its I2C assessable registers. When the device is soft reset it takes 2ms to boot up (as per general electrical specifications Table 1) then performs a reload of its trimming parameters from NVM. the status register contains a status bit for tracking the completion of its load from NVM. We need to wait for the status bit to clear before reading out the trimming parameters. The new implementation of the reset function performs the necessary backoffs and status checks to ensure the device is ready to read out its trimming values.

Furthermore this PR adds boiler plate generated by CubeMX to address the clock configuration for the HAL library. This includes the `system32h7xx_hal_timebase_tim.c` which implements:
1.  Initializes the TIM peripheral generate a period elapsed event each 1ms
2. `HAL_IncTick` is called inside `HAL_TIM_PeriodElapsedCallback` ie each 1ms

## Resolutions
 - [x] Fixed #35  by adding backoff and polling for the IM_UPDATE bit in the status register on sensor reset.
 - [x] Fixed #36 which addresses the HAL clock configuration in the context of the FreeRTOS runtime.

## Issues
closes #35 
closes #36

### CODE REVIEW

File: src/drivers/bme280.c [hunk 1]
```diff
@@ -19,6 +19,189 @@
...
+  return status;
+}
+
+/**
+ * @brief Execute a sensor read using triggering (forced mode)
+ */
+bme280_status_t bme280_trigger_read(bme280_dev_t *dev, bme280_meas_t *measurements) {
+  uint32_t msb;
+  uint32_t lsb;
+  uint32_t xlsb;
```
Comment (BrandonLucasZhu) [inline src/drivers/bme280.c:165]: Should you initialize here?

**Review by BrandonLucasZhu — APPROVED** [review]
